### PR TITLE
Update command system

### PR DESCRIPTION
**Pull request by MrLotU**
Update command system to accept a command both when it's spelled like this: `!command` but also if you were to throw in some random caps like this: `!cOMMand` also works when you `.register` a command, can put in both `bot.register("coMMand")` and `bot.register("command")`

### CODE REVIEW

**Comment by Azoy** [comment]
Few things here that I see
1. Needs to compile
2. Use 2 space tabs
3. You're not guaranteed that someone registered their command using all lowercase

**Comment by MrLotU** [comment]
1. I figured that out, working on that now
2. /tableflip
3. What do you mean?

**Comment by MrLotU** [comment]
Just seeing if it works now, I'll fix indention in a bit

**Comment by MrLotU** [comment]
Need to do more local testing of the `handle()` method, I'll reopen once that's fixed

**Pull request closed without merging**
